import type { NodeType, NodeTypeDefinition, NodeCategory } from '../../types'

export const NODE_CATEGORIES: NodeCategory[] = [
  {
    id: 'trigger',
    label: 'Triggers',
    color: '#f59e0b',
    types: [
      {
        type: 'trigger:manual',
        label: 'Manual Trigger',
        description: 'Start pipeline manually',
        icon: 'zap',
        category: 'trigger',
        color: '#f59e0b',
        defaultConfig: {},
      },
      {
        type: 'trigger:cron',
        label: 'Cron Trigger',
        description: 'Schedule pipeline with cron expression',
        icon: 'clock',
        category: 'trigger',
        color: '#f59e0b',
        defaultConfig: { schedule: '0 * * * *', timezone: 'UTC' },
      },
      {
        type: 'trigger:webhook',
        label: 'Webhook Trigger',
        description: 'Trigger pipeline via HTTP webhook',
        icon: 'webhook',
        category: 'trigger',
        color: '#f59e0b',
        defaultConfig: { path: '', method: 'POST' },
      },
      {
        type: 'trigger:channel_message',
        label: 'Channel Message',
        description: 'Trigger when a connected channel user sends a message',
        icon: 'message-square',
        category: 'trigger',
        color: '#f59e0b',
        defaultConfig: { channelId: '' },
      },
    ],
  },
  {
    id: 'action',
    label: 'Actions',
    color: '#10b981',
    types: [
      {
        type: 'action:proxmox_list_nodes',
        label: 'List Nodes',
        description: 'List nodes in a selected Proxmox cluster',
        icon: 'globe',
        category: 'action',
        color: '#10b981',
        defaultConfig: { clusterId: '' },
      },
      {
        type: 'action:proxmox_list_workloads',
        label: 'List VMs/CTs',
        description: 'List virtual machines and containers in a cluster',
        icon: 'link',
        category: 'action',
        color: '#10b981',
        defaultConfig: { clusterId: '', node: '' },
      },
      {
        type: 'action:vm_start',
        label: 'Start VM',
        description: 'Start a Proxmox VM',
        icon: 'play',
        category: 'action',
        color: '#10b981',
        defaultConfig: { clusterId: '', node: '', vmid: 0 },
      },
      {
        type: 'action:vm_stop',
        label: 'Stop VM',
        description: 'Stop a Proxmox VM immediately',
        icon: 'square',
        category: 'action',
        color: '#10b981',
        defaultConfig: { clusterId: '', node: '', vmid: 0 },
      },
      {
        type: 'action:vm_clone',
        label: 'Clone VM',
        description: 'Clone a Proxmox VM',
        icon: 'copy',
        category: 'action',
        color: '#10b981',
        defaultConfig: { clusterId: '', node: '', vmid: 0, newName: '', newId: 0 },
      },
      {
        type: 'action:http',
        label: 'HTTP Request',
        description: 'Make an HTTP request',
        icon: 'globe',
        category: 'action',
        color: '#10b981',
        defaultConfig: { url: '', method: 'GET', headers: {}, body: '' },
      },
      {
        type: 'action:shell_command',
        label: 'Shell Command',
        description: 'Run a local shell command in the workspace',
        icon: 'code',
        category: 'action',
        color: '#10b981',
        defaultConfig: { command: '', workingDirectory: '', timeoutSeconds: 60 },
      },
      {
        type: 'action:lua',
        label: 'Lua Script',
        description: 'Execute custom Lua code',
        icon: 'code',
        category: 'action',
        color: '#10b981',
        defaultConfig: { script: '-- Write your Lua code here\nreturn { status = "ok" }' },
      },
      {
        type: 'action:channel_send_message',
        label: 'Send Channel Message',
        description: 'Send a reply or outbound message through an active channel',
        icon: 'send',
        category: 'action',
        color: '#10b981',
        defaultConfig: { channelId: '', recipient: '', message: '' },
      },
      {
        type: 'action:channel_send_and_wait',
        label: 'Send And Wait',
        description: 'Send a channel message and wait for the user reply',
        icon: 'message-square',
        category: 'action',
        color: '#10b981',
        defaultConfig: { channelId: '', recipient: '', message: '', timeoutSeconds: 300 },
      },
      {
        type: 'action:pipeline_run',
        label: 'Run Pipeline',
        description: 'Run another pipeline manually and pass JSON parameters',
        icon: 'workflow',
        category: 'action',
        color: '#10b981',
        defaultConfig: { pipelineId: '', params: '' },
      },
    ],
  },
  {
    id: 'tool',
    label: 'Tools',
    color: '#38bdf8',
    types: [
      {
        type: 'tool:proxmox_list_nodes',
        label: 'List Nodes Tool',
        description: 'Expose a tool that lists nodes in a selected Proxmox cluster',
        icon: 'globe',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { clusterId: '' },
      },
      {
        type: 'tool:proxmox_list_workloads',
        label: 'List VMs/CTs Tool',
        description: 'Expose a tool that lists workloads in a selected Proxmox cluster',
        icon: 'link',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { clusterId: '', node: '' },
      },
      {
        type: 'tool:vm_start',
        label: 'Start VM Tool',
        description: 'Expose a tool that starts a VM in a selected Proxmox cluster',
        icon: 'play',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { clusterId: '', node: '', vmid: 0 },
      },
      {
        type: 'tool:vm_stop',
        label: 'Stop VM Tool',
        description: 'Expose a tool that stops a VM in a selected Proxmox cluster',
        icon: 'square',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { clusterId: '', node: '', vmid: 0 },
      },
      {
        type: 'tool:vm_clone',
        label: 'Clone VM Tool',
        description: 'Expose a tool that clones a VM in a selected Proxmox cluster',
        icon: 'copy',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { clusterId: '', node: '', vmid: 0, newName: '', newId: 0 },
      },
      {
        type: 'tool:http',
        label: 'HTTP Request Tool',
        description: 'Expose a tool that makes HTTP requests',
        icon: 'globe',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { url: '', method: 'GET', headers: {}, body: '' },
      },
      {
        type: 'tool:shell_command',
        label: 'Shell Command Tool',
        description: 'Expose a tool that runs local shell commands in the workspace',
        icon: 'code',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { command: '', workingDirectory: '', timeoutSeconds: 60 },
      },
      {
        type: 'tool:pipeline_list',
        label: 'List Pipelines Tool',
        description: 'Expose a tool that lists available pipelines to an agent',
        icon: 'list',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: {},
      },
      {
        type: 'tool:pipeline_create',
        label: 'Create Pipeline Tool',
        description: 'Expose a tool that creates new pipelines',
        icon: 'workflow',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { toolName: '', toolDescription: '' },
      },
      {
        type: 'tool:pipeline_update',
        label: 'Update Pipeline Tool',
        description: 'Expose a tool that updates existing pipelines',
        icon: 'wrench',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { toolName: '', toolDescription: '' },
      },
      {
        type: 'tool:pipeline_delete',
        label: 'Delete Pipeline Tool',
        description: 'Expose a tool that deletes pipelines',
        icon: 'trash-2',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { toolName: '', toolDescription: '' },
      },
      {
        type: 'tool:pipeline_run',
        label: 'Run Pipeline Tool',
        description: 'Expose a tool that runs a selected pipeline and returns its output',
        icon: 'wrench',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { pipelineId: '', toolName: '', toolDescription: '', allowModelPipelineId: false },
      },
      {
        type: 'tool:channel_send_and_wait',
        label: 'Send And Wait Tool',
        description: 'Expose a tool that messages a channel user and waits for their reply',
        icon: 'message-square',
        category: 'tool',
        color: '#38bdf8',
        defaultConfig: { channelId: '', recipient: '', message: '', timeoutSeconds: 300 },
      },
    ],
  },
  {
    id: 'logic',
    label: 'Logic',
    color: '#8b5cf6',
    types: [
      {
        type: 'logic:condition',
        label: 'Condition',
        description: 'Evaluate a condition (if/else)',
        icon: 'git-branch',
        category: 'logic',
        color: '#8b5cf6',
        defaultConfig: { expression: '' },
      },
      {
        type: 'logic:switch',
        label: 'Switch',
        description: 'Evaluate multiple conditions and fan out to every matching branch',
        icon: 'split',
        category: 'logic',
        color: '#8b5cf6',
        defaultConfig: {
          conditions: [
            {
              id: 'condition-1',
              label: 'Condition 1',
              expression: '',
            },
          ],
        },
      },
      {
        type: 'logic:merge',
        label: 'Merge',
        description: 'Merge multiple upstream object outputs into one payload',
        icon: 'workflow',
        category: 'logic',
        color: '#8b5cf6',
        defaultConfig: { mode: 'shallow' },
      },
      {
        type: 'logic:aggregate',
        label: 'Aggregate',
        description: 'Collect multiple upstream outputs into ordered arrays with source metadata',
        icon: 'list',
        category: 'logic',
        color: '#8b5cf6',
        defaultConfig: {},
      },
      {
        type: 'logic:return',
        label: 'Return',
        description: 'Return data from this pipeline to the caller and stop execution',
        icon: 'corner-down-left',
        category: 'logic',
        color: '#8b5cf6',
        defaultConfig: { value: '' },
      },
    ],
  },
  {
    id: 'llm',
    label: 'LLM',
    color: '#ec4899',
    types: [
      {
        type: 'llm:prompt',
        label: 'LLM Prompt',
        description: 'Send a prompt to an LLM provider',
        icon: 'brain',
        category: 'llm',
        color: '#ec4899',
        defaultConfig: { providerId: '', prompt: '', model: '', temperature: 0.7, max_tokens: 1024 },
      },
      {
        type: 'llm:agent',
        label: 'LLM Agent',
        description: 'Run a multi-turn LLM agent with connected tool nodes',
        icon: 'bot',
        category: 'llm',
        color: '#ec4899',
        defaultConfig: { providerId: '', prompt: '', model: '', temperature: 0.7, max_tokens: 1024, enableSkills: false },
      },
    ],
  },
]

export const NODE_TYPE_MAP: Record<NodeType, NodeTypeDefinition> = NODE_CATEGORIES.reduce(
  (acc, cat) => {
    cat.types.forEach((t) => {
      acc[t.type] = t
    })
    return acc
  },
  {} as Record<NodeType, NodeTypeDefinition>
)

export function getNodeColor(type: NodeType): string {
  return NODE_TYPE_MAP[type]?.color || '#6b7280'
}

export function getNodeLabel(type: NodeType): string {
  return NODE_TYPE_MAP[type]?.label || type
}

export function getNodeIcon(type: NodeType): string {
  return NODE_TYPE_MAP[type]?.icon || 'circle'
}
